### ISSUE TITLE
Will this conflict with jQuery's built-in `after`?

### ISSUE THREAD

**Issue by suzaku** [avk/jQuery-Chrono#1]
http://api.jquery.com/after/

**Comment by avk** [comment]
Chrono's after doesn't conflict with jQuery's built-in after because they're in different namespaces. jQuery's built-in after is in the jQuery.fn namespace, which means it only operates on jQuery objects that reference DOM elements. 

It's like the difference between [jQuery.each](http://api.jquery.com/jQuery.each/) and [jQuery(elements).each](http://api.jquery.com/each/).

If you experience them conflicting in any way, please do let me know.

**Comment by janhartigan** [comment]
It appears that they do not, as you can see here:

http://jsfiddle.net/treeface/5Pxyc/1/

This library uses 

<pre>
$.extend({
    after: after,
    every: every
});
</pre>


Instead of $.fn.extend. With $.extend, it just adds the functions to the jQuery object, accessible with $.after. The core jQuery after is created using $.fn.extend and is thus added to the jQuery.fn object, accessible with $(selector).after.
